// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type RssFeed struct {
	ID             int64     `json:"id"`
	Title          string    `json:"title"`
	Url            string    `json:"url"`
	ReferenceCount int64     `json:"reference_count"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type RssFeedItem struct {
	ID          int64     `json:"id"`
	RssFeedID   int64     `json:"rss_feed_id"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
	PublishedAt time.Time `json:"published_at"`
	AddedAt     time.Time `json:"added_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserView struct {
	UserID    int64     `json:"user_id"`
	ViewID    int64     `json:"view_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type View struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Public    bool      `json:"public"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ViewItem struct {
	ID        int64     `json:"id"`
	ViewID    int64     `json:"view_id"`
	FeedID    int64     `json:"feed_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
